camera:
  depth:
    accuracy:
      max: 100
      min: 90
    fps:
      max: 60
      min: 30
    ideal_range:
      max: 4.0
      min: 0.5
    min_depth_distance: 0.5
    resolution: 720p
  infrared:
    enabled: true
    fps:
      max: 60
      min: 30
  rgb:
    fps:
      max: 60
      min: 30
    resolution: 1080p
  topic: camera_stream
